# Generated by Django 4.2.7 on 2023-11-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_respuesta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(choices=[('1', 'Nunca'), ('2', 'Casi nunca'), ('3', 'A veces'), ('4', 'Casi siempre'), ('5', 'Siempre')], default='1', max_length=10),
        ),
    ]
